# Generated by Django 6.0 on 2025-12-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
    ]
